// 1
// Add Variables Here

// Ouput
console.log("Add Code Here"); // Normal Concatenate => 1020
console.log("Add Code Here"); // Normal Concatenate => String
console.log("Add Code Here"); // Template Literals Way => 1020
console.log("Add Code Here"); // Template Literals Way => String

console.log("Add Code Here");
/*
  Normal Concatenate
  20
  10
*/

console.log("Add Code Here");
/*
  Template Literals Way
  20
  10
*/